services:
  caramel-api:
    image: caramel-api
    build:
      context: .
      dockerfile: src/Caramel.API/Dockerfile
    ports:
      - 5144:5144
    env_file:
      - .env
    depends_on:
      - caramel-service
      - redis
    networks:
      - caramel

  caramel-discord:
    image: caramel-discord
    build:
      context: .
      dockerfile: src/Caramel.Discord/Dockerfile
    ports:
      - 5145:5145
    env_file:
      - .env
    depends_on:
      - caramel-service
      - redis
    networks:
      - caramel

  caramel-twitch:
    image: caramel-twitch
    build:
      context: .
      dockerfile: src/Caramel.Twitch/Dockerfile
    ports:
      - 5146:5146
    env_file:
      - .env
    depends_on:
      - caramel-service
      - redis
    networks:
      - caramel

  caramel-service:
    image: caramel-service
    build:
      context: .
      dockerfile: src/Caramel.Service/Dockerfile
    ports:
      - 5270:5270
    env_file:
      - .env
    depends_on:
      - pgsql
      - redis
    networks:
      - caramel

  pgsql:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-caramel}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-caramel}
      - POSTGRES_DB=${POSTGRES_DB:-caramel_db}
    volumes:
      - pgsql_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - caramel

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:-caramel_redis}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - caramel
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  pgsql_data:
  redis_data:

networks:
  caramel:
    driver: bridge
